<?php

			$map = array(
				'patient_info' => 'Patients Info',
				'p_id' => 'Patient ID',
				'gender' => 'Gender',
				'name' => 'Name',
				'age' => 'Age',
				'phone' => 'Phone',
				'patient_history' => 'Patient History',
				'treated_by' => "Patient's doctor",
				'diagnosis_info' => "Diagnosis Information",
				'doctors_info' => "Doctors  Info",
				'checkup_type' => "Type of checkup",
				'e_id' => "Employee ID",
				'sample_id' => "Sample Number",
				'doctor_id' => "Doctor ID",
				'fees' => "Fees of Doctor",
				'specialisation' => "Specialisation of Doctor",
				'address' => 'Address',
				'type' => 'Type of Employee',
				'off_day' => 'Off day',
				'duty_start_time' => 'Duty start time',
				'duty_end_time' => 'Duty end time',
				'date_of_admit' => 'Admit Date',
				'date_of_discharge' => 'Discharge Date',
				'occupancy_type' => 'Facilities availed',
				'medical_cost' => 'Medical cost',
				'room_number' => 'Room Number',
				'employees_info' => 'Employees Info',
				'patient_occupancy' => 'Patients Occupancy',
			);
?>
